version: '3'
services:
 scrape:
  container_name: scrape_cron
  build:
    context: .
    dockerfile: Dockerfile.arm
#   dockerfile: Dockerfile.amd64
  entrypoint: crond -f -l 2 -L /dev/stdout
  volumes:
    - /home/pi/surflog:/opt/surflog/host:rw
  environment:
    - TZ=Europe/Stockholm
